//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "usonic.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "driverlib/timer.h"
#include "driverlib/interrupt.h"
#include "inc/tm4c123gh6pm.h"

uint32_t start, stop, time, distance1 = 0, distance2 = 0, distance3 = 0;

#define RED 0x02
#define BLUE 0x04
#define GREEN 0x08
#define REDPIN GPIO_PIN_1
#define BLUEPIN GPIO_PIN_2
#define GREENPIN GPIO_PIN_3

//*****************************************************************************
void
PortFunctionInit(void)
{
    // Enable Peripheral Clocks 
	  SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	
    GPIOPinTypeGPIOInput(GPIO_PORTB_BASE, GPIO_PIN_2); // Enable pin PB2 for GPIOInput -- hook up echo 1
	  GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_1);  //Enable pin PB1 for GPIOOutput -- hook up trig 1
	
		GPIOPinTypeGPIOInput(GPIO_PORTB_BASE, GPIO_PIN_0); // Enable pin PB0 for GPIOInput -- hook up echo 2
	  GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_3);  //Enable pin PB3 for GPIOOutput -- hook up trig 2
	
//		GPIOPinTypeGPIOInput(GPIO_PORTB_BASE, GPIO_PIN_5); // Enable pin PB5 for GPIOInput -- hook up echo 3
//	  GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_4);  //Enable pin PB4 for GPIOOutput -- hook up trig 3
	
		// enable LEDS for output 
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);

}
// Timer Init
void Timer0A_Init(void)
{
//	SysCtlClockSet(SYSCTL_SYSDIV_10 | SYSCTL_USE_PLL |  SYSCTL_XTAL_16MHZ | SYSCTL_OSC_MAIN); // set clock to 20MHz
	TimerConfigure(TIMER0_BASE, TIMER_CFG_PERIODIC); // configure timer
	TimerClockSourceSet(TIMER0_BASE, TIMER_CLOCK_SYSTEM);
	TimerLoadSet(TIMER0_BASE, TIMER_A, 1999999); // reload value into timer
	IntPrioritySet(INT_TIMER0A, 0x01); // timer has priority 
	IntEnable(INT_TIMER0A); // enable interuupt
	TimerIntEnable(TIMER0_BASE, TIMER_TIMA_TIMEOUT); // ARM timeout interrupt
	TimerEnable(TIMER0_BASE, TIMER_A); // enable subtimer 0A of timer 0

}

void getDistanceOne(void){
	
	while(!GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_2)){} // while echo is low, do nothing
	start = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes high, record value as start time
	while(GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_2)){} // while echo is high, do nothing
	stop = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes low, record value as end time
	time = start - stop; // time echo was high
	distance1 = time / 942; // calculate distance based on time, clock freq, and speed of sound
	
}

void getDistanceTwo(void){
	
	while(!GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_0)){} // while echo is low, do nothing
	start = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes high, record value as start time
	while(GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_0)){} // while echo is high, do nothing
	stop = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes low, record value as end time
	time = start - stop; // time echo was high
	distance2 = time / 942; // calculate distance based on time, clock freq, and speed of sound
	
}


void getDistanceThree(void){
	
	while(!GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_5)){} // while echo is low, do nothing
	start = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes high, record value as start time
	while(GPIOPinRead(GPIO_PORTB_BASE,GPIO_PIN_5)){} // while echo is high, do nothing
	stop = TimerValueGet(TIMER0_BASE, TIMER_A); // when echo becomes low, record value as end time
	time = start - stop; // time echo was high
	distance3 = time / 942; // calculate distance based on time, clock freq, and speed of sound
	
}

void Timer0A_Handler(void)
{
	// generate Trig pulse for Sensor 1
	TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_1, 0x00); // trig 1 low
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_3, 0x00); // trig 2 low
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_4, 0x00); // trig 3 low
	SysCtlDelay(80); // wait 
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_1, 0x02); // trig 1 high
	SysCtlDelay(80); // wait
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_1, 0x00); // trig 1 low
	
	getDistanceOne();
	
	// generate Trig pulse for Sensor 2
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_3, 0x08); // trig 2 high
	SysCtlDelay(80); // wait
	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_3, 0x00); // trig 2 low
	
	getDistanceTwo();
	
//	// generate Trig pulse for Sensor 3
//	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_4, 0x10); // trig 3 high
//	SysCtlDelay(80); // wait
//	GPIOPinWrite(GPIO_PORTB_BASE, GPIO_PIN_4, 0x00); // trig 3 low
//	
//	getDistanceThree();
//	
}


int main(void)
{
	PortFunctionInit();
	Timer0A_Init();
	IntMasterEnable();
	
	while(1){
		
		
		if((distance1 >= 2 && distance1 <= 15))
		{
			GPIOPinWrite(GPIO_PORTF_BASE, REDPIN, RED);
		}
		else {
			GPIOPinWrite(GPIO_PORTF_BASE, REDPIN, 0x00);
			
		}
		
		if((distance2 >= 2 && distance2 <= 15))
		{
			GPIOPinWrite(GPIO_PORTF_BASE, BLUEPIN, BLUE);
		}
		else {
			GPIOPinWrite(GPIO_PORTF_BASE, BLUEPIN, 0x00);
		}
		
		if((distance3 >= 2 && distance3 <= 15))
		{
			GPIOPinWrite(GPIO_PORTF_BASE, GREENPIN, GREEN);
		}
		else {
			GPIOPinWrite(GPIO_PORTF_BASE, GREENPIN, 0x00);
		}
	}
}

